### ISSUE TITLE
Not able to download 10.7 bootstrap installer

### ISSUE THREAD

**Issue by yingchenjun** [SoftwareAG/sagdevops-cc-server#11]
I’m trying to automate command central 10.7 setup.  I’m receiving below error. Can you help confirm if 10.7 bootstrap installer is available?

The 
![error](https://user-images.githubusercontent.com/34504796/127578771-e4925365-8194-4486-9d96-f154f1a50c92.png)

https://github.com/SoftwareAG/sagdevops-cc-server/tree/release/107oct2020

**Comment by yingchenjun** [comment]
in the default.properties, I have to change installer.url from http to https. The issue is resolved. 

installer.url=http://empowersdc.softwareag.com/ccinstallers

**Comment by YanaSimeonova** [comment]
> in the default.properties, I have to change installer.url from http to https. The issue is resolved.
> 
> installer.url=http://empowersdc.softwareag.com/ccinstallers

Thank you for pointing this out! The default value is now changed.
