### ISSUE TITLE
Connection reset

### ISSUE THREAD

**Issue by mreys** [SoftwareAG/sagdevops-cc-server#9]
There's a connection reset in the 'ant boot -Daccept.license=true' step.
The issue is in the download of the following script: http://empowersdc.softwareag.com/ccinstallers/cc-def-10.5-latest-lnxamd64.sh

When testing with curl, I get the following:
` curl -v http://empowersdc.softwareag.com/ccinstallers/cc-def-10.5-latest-lnxamd64.sh
*   Trying 157.189.192.104...
* TCP_NODELAY set
* Connected to empowersdc.softwareag.com (157.189.192.104) port 80 (#0)
> GET /ccinstallers/cc-def-10.5-latest-lnxamd64.sh HTTP/1.1
> Host: empowersdc.softwareag.com
> User-Agent: curl/7.61.1
> Accept: */*
>
* Recv failure: Connection reset by peer
* Closing connection 0
curl: (56) Recv failure: Connection reset by peer
`

I tried from multiple machines, different networks but I fear the problem is with the server.

**Comment by bpaskalev** [comment]
Thank you for reporting this.

Should be fixed now.

Please clone the project again with --recursive, because the issue was in a submodule ( sagdevops-antcc)
The reason was that the empower server was moved from http to https.
Let us know it if works for you

**Comment by bpaskalev** [comment]
Closing the issue, as there were no reply.
If the issue appears again, feel free to reopen it.

Bisser
